spring:
  application:
    name: haoke-im
  data:
    mongodb:
      uri: mongodb://vagrant:27017/testdb
  rocketmq:
    nameServer: vagrant:9876;vagrant:9877
    producer:
      group: haoke-im-websocket-group
    elasticsearch:
      cluster-name: es-itcast-cluster
      cluster-nodes: vagrant:9300,vagrant:9301,vagrant:9302
server:
  port: 18081
